# Generated by Django 4.1.7 on 2023-04-03 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platoprincipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_receta', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Postre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_receta', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Singluten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_receta', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vegano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_receta', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name='Dulce',
            new_name='Entrada',
        ),
        migrations.RenameField(
            model_name='entrada',
            old_name='nombrereceta',
            new_name='nombre_receta',
        ),
    ]
