# Generated by Django 4.1.7 on 2023-04-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0003_alter_entrada_nombre_receta'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='duracion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entrada',
            name='ingredientes',
            field=models.CharField(default=' ', max_length=60),
        ),
        migrations.AddField(
            model_name='entrada',
            name='procedimiento',
            field=models.CharField(default=' ', max_length=500),
        ),
    ]
