# Generated by Django 4.1.7 on 2023-04-09 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0005_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='platoprincipal',
            name='duracion',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AddField(
            model_name='platoprincipal',
            name='ingredientes',
            field=models.CharField(default=' ', max_length=60),
        ),
        migrations.AddField(
            model_name='platoprincipal',
            name='procedimiento',
            field=models.CharField(default=' ', max_length=500),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='duracion',
            field=models.CharField(default=' ', max_length=20),
        ),
    ]
